// tm7-recipes.js – TM7 Rezeptdatenbank: Mittagessen + Snacks
// VERSION: 1.0
// Erweiterbar: einfach weitere Objekte ins Array TM7_RECIPES einfügen.
//
// Felder pro Rezept:
// id          eindeutige ID (string)
// name        Rezeptname
// type        "mittag" | "snack"
// season      Array: ["sommer","herbst","winter","fruehling"] oder ["ganzjahr"]
// portionsBase Anzahl Portionen, für die die Zutatenliste unten gilt (meist 1)
// ingredients  Array von {item, grams, unit} – grams ist die Menge PRO PORTION (portionsBase=1),
//              damit beim Hochskalieren auf 2/3/4 Portionen einfach grams*portionen gerechnet wird
// tm7Steps     Array von Schritt-Strings, TM7-spezifisch (Stufe/Zeit/Temperatur wo sinnvoll)
// seasonalSwap Optional: {von: "Zutat", alternativen: {sommer:"X", winter:"Y", ...}}
// tasteTags    Array, zur Filterung nach Geschmacksprofil (z.B. "haehnchen","linsen","wenig_fisch_ok")

const TM7_RECIPES_VERSION="1.0";
const TM7_RECIPES=[
  {
    id:"haehnchen-gemuese-reis",
    name:"Hähnchen-Gemüse-Reis-Pfanne",
    type:"mittag",
    season:["ganzjahr"],
    portionsBase:1,
    ingredients:[
      {item:"Hähnchenbrust",grams:150,unit:"g"},
      {item:"Naturreis",grams:60,unit:"g (roh)"},
      {item:"Brokkoli",grams:100,unit:"g"},
      {item:"Karotte",grams:50,unit:"g"},
      {item:"Paprika rot",grams:50,unit:"g"},
      {item:"Olivenöl",grams:10,unit:"g"},
      {item:"Knoblauch",grams:5,unit:"g"},
    ],
    tm7Steps:[
      "Reis mit 200g Wasser in den Varoma-Topf geben, im Mixtopf 400g Wasser, Reis 20 Min/Varoma/Stufe 1 dämpfen.",
      "Hähnchenbrust in Würfel schneiden, mit Olivenöl und Knoblauch 3 Min/120°C/Stufe 1 im Mixtopf anbraten (Linkslauf).",
      "Gemüse grob würfeln, in den Varoma-Einsatz über das Hähnchen geben, 10 Min/Varoma/Stufe 1 dämpfen.",
      "Alles zusammen in einer Schüssel mit dem Reis vermengen, salzen, pfeffern.",
    ],
    seasonalSwap:{von:"Brokkoli",alternativen:{sommer:"Zucchini",herbst:"Blumenkohl",winter:"Rosenkohl",fruehling:"Brokkoli"}},
    tasteTags:["haehnchen","reis","gemuese_viel"],
  },
  {
    id:"linsen-curry",
    name:"Rote-Linsen-Gemüse-Curry",
    type:"mittag",
    season:["ganzjahr"],
    portionsBase:1,
    ingredients:[
      {item:"Linsen gekocht",grams:150,unit:"g (oder 60g roh)"},
      {item:"Tomaten",grams:100,unit:"g (oder 1 Dose/4 Portionen)"},
      {item:"Karotte",grams:60,unit:"g"},
      {item:"Zwiebel",grams:30,unit:"g"},
      {item:"Knoblauch",grams:5,unit:"g"},
      {item:"Kurkuma",grams:2,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Zwiebel und Knoblauch grob halbieren, 5 Sek/Stufe 5 zerkleinern.",
      "Olivenöl zugeben, 3 Min/120°C/Stufe 1 anschwitzen.",
      "Linsen, Tomaten, Karotte (gewürfelt) und Kurkuma zugeben, 20 Min/100°C/Stufe 1 (Linkslauf) köcheln.",
      "Mit Salz und Pfeffer abschmecken, optional mit Naturreis oder Dinkel servieren.",
    ],
    seasonalSwap:{von:"Karotte",alternativen:{sommer:"Zucchini",herbst:"Kürbis",winter:"Pastinake",fruehling:"Karotte"}},
    tasteTags:["linsen","vegetarisch","gemuese_viel","ballaststoffreich"],
  },
  {
    id:"pute-quinoa-bowl",
    name:"Puten-Quinoa-Bowl mit Spinat",
    type:"mittag",
    season:["ganzjahr"],
    portionsBase:1,
    ingredients:[
      {item:"Putenbrust",grams:150,unit:"g"},
      {item:"Quinoa gekocht",grams:150,unit:"g (oder 50g roh)"},
      {item:"Spinat",grams:80,unit:"g"},
      {item:"Tomaten",grams:60,unit:"g"},
      {item:"Feta",grams:30,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Quinoa im Varoma mit 300g Wasser im Mixtopf 15 Min/Varoma/Stufe 1 dämpfen.",
      "Putenbrust würfeln, mit etwas Olivenöl 4 Min/Varoma/Stufe 1 im Varoma-Einsatz mitdämpfen (oder kurz anbraten).",
      "Spinat die letzten 2 Minuten dazugeben, kurz zusammenfallen lassen.",
      "Quinoa, Pute, Spinat, Tomaten in Bowl anrichten, Feta drüber, Olivenöl darüber.",
    ],
    seasonalSwap:{von:"Spinat",alternativen:{sommer:"Rucola",herbst:"Grünkohl",winter:"Grünkohl",fruehling:"Spinat"}},
    tasteTags:["pute","quinoa","gemuese_viel"],
  },
  {
    id:"kichererbsen-eintopf",
    name:"Mediterraner Kichererbsen-Eintopf",
    type:"mittag",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Kichererbsen gekocht",grams:150,unit:"g"},
      {item:"Tomaten",grams:100,unit:"g"},
      {item:"Zucchini",grams:80,unit:"g"},
      {item:"Paprika rot",grams:50,unit:"g"},
      {item:"Knoblauch",grams:5,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
      {item:"Oregano",grams:1,unit:"g"},
    ],
    tm7Steps:[
      "Gemüse in groben Stücken in den Mixtopf geben, mit Olivenöl 3 Min/120°C/Stufe 1 anbraten.",
      "Kichererbsen und Tomaten zugeben, 15 Min/100°C/Stufe 1 (Linkslauf) köcheln.",
      "Mit Oregano, Salz, Pfeffer abschmecken.",
    ],
    seasonalSwap:{von:"Zucchini",alternativen:{sommer:"Zucchini",herbst:"Aubergine",winter:"Sellerie",fruehling:"Zucchini"}},
    tasteTags:["kichererbsen","vegetarisch","gemuese_viel","ballaststoffreich"],
  },
  {
    id:"lachs-ofengemuese",
    name:"Lachs mit Ofengemüse (Variante ohne TM-Garung)",
    type:"mittag",
    season:["ganzjahr"],
    portionsBase:1,
    ingredients:[
      {item:"Lachs",grams:150,unit:"g"},
      {item:"Süßkartoffel",grams:150,unit:"g"},
      {item:"Brokkoli",grams:100,unit:"g"},
      {item:"Olivenöl",grams:10,unit:"g"},
      {item:"Zitrone",grams:20,unit:"g"},
    ],
    tm7Steps:[
      "Süßkartoffel würfeln, im Varoma 20 Min/Varoma/Stufe 1 dämpfen (Mixtopf: 500g Wasser).",
      "Brokkoli die letzten 10 Minuten dazugeben.",
      "Lachs parallel in der Pfanne oder im Ofen (200°C, 12 Min) garen – TM7 eignet sich hier primär für die Beilagen.",
      "Alles mit Olivenöl und Zitrone anrichten.",
    ],
    seasonalSwap:{von:"Süßkartoffel",alternativen:{sommer:"Kartoffel",herbst:"Süßkartoffel",winter:"Pastinake",fruehling:"Kartoffel"}},
    tasteTags:["lachs","wenig_fisch_ok","gemuese_viel"],
  },
  {
    id:"hirsebrei-gemuese",
    name:"Herzhafter Hirse-Gemüse-Brei",
    type:"mittag",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Hirse",grams:60,unit:"g (roh)"},
      {item:"Karotte",grams:60,unit:"g"},
      {item:"Lauch",grams:40,unit:"g"},
      {item:"Hähnchenbrust",grams:100,unit:"g"},
      {item:"Gemüsebrühe",grams:300,unit:"ml"},
    ],
    tm7Steps:[
      "Karotte und Lauch grob schneiden, 5 Sek/Stufe 4 zerkleinern.",
      "Hirse, Gemüsebrühe und Hähnchen (gewürfelt) zugeben, 20 Min/100°C/Stufe 1 (Linkslauf) köcheln.",
      "Mit Salz, Pfeffer und etwas Petersilie abschmecken.",
    ],
    seasonalSwap:{von:"Lauch",alternativen:{sommer:"Frühlingszwiebel",herbst:"Lauch",winter:"Lauch",fruehling:"Frühlingszwiebel"}},
    tasteTags:["haehnchen","gemuese_viel"],
  },
  {
    id:"weisse-bohnen-tomatensauce",
    name:"Weiße Bohnen in Tomatensauce mit Dinkel",
    type:"mittag",
    season:["ganzjahr"],
    portionsBase:1,
    ingredients:[
      {item:"Weiße Bohnen",grams:150,unit:"g"},
      {item:"Tomaten",grams:120,unit:"g"},
      {item:"Knoblauch",grams:5,unit:"g"},
      {item:"Dinkel Vollkornmehl",grams:60,unit:"g (als Dinkelreis/-grütze, roh)"},
      {item:"Olivenöl",grams:8,unit:"g"},
      {item:"Rosmarin",grams:1,unit:"g"},
    ],
    tm7Steps:[
      "Knoblauch fein hacken, mit Olivenöl 2 Min/120°C/Stufe 1 anschwitzen.",
      "Tomaten und Bohnen zugeben, 15 Min/100°C/Stufe 1 (Linkslauf) köcheln.",
      "Mit Rosmarin, Salz, Pfeffer würzen. Dinkel separat als Beilage kochen.",
    ],
    tasteTags:["weisse_bohnen","vegetarisch","ballaststoffreich"],
  },
  {
    id:"kidneybohnen-chili",
    name:"Mildes Kidneybohnen-Chili (ohne Fleisch)",
    type:"mittag",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Kidneybohnen",grams:150,unit:"g"},
      {item:"Tomaten",grams:120,unit:"g"},
      {item:"Paprika rot",grams:60,unit:"g"},
      {item:"Zwiebel",grams:30,unit:"g"},
      {item:"Mais",grams:50,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Zwiebel und Paprika grob würfeln, mit Olivenöl 3 Min/120°C/Stufe 1 anbraten.",
      "Bohnen, Tomaten und Mais zugeben, 15 Min/100°C/Stufe 1 (Linkslauf) köcheln.",
      "Abschmecken mit Salz, Pfeffer, optional etwas Paprikapulver.",
    ],
    seasonalSwap:{von:"Paprika rot",alternativen:{sommer:"Paprika rot",herbst:"Kürbis",winter:"Kürbis",fruehling:"Paprika rot"}},
    tasteTags:["vegetarisch","gemuese_viel","ballaststoffreich"],
  },
  {
    id:"kabeljau-gemuesepfanne",
    name:"Kabeljau-Gemüsepfanne mit Naturreis",
    type:"mittag",
    season:["sommer","fruehling"],
    portionsBase:1,
    ingredients:[
      {item:"Kabeljau",grams:150,unit:"g"},
      {item:"Naturreis",grams:60,unit:"g (roh)"},
      {item:"Zucchini",grams:80,unit:"g"},
      {item:"Paprika gelb",grams:50,unit:"g"},
      {item:"Knoblauch",grams:5,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Reis im Varoma mit 200g Wasser im Mixtopf (400g Wasser) 20 Min/Varoma/Stufe 1 dämpfen.",
      "Gemüse würfeln, mit Olivenöl und Knoblauch 4 Min/Varoma/Stufe 1 mitdämpfen oder in der Pfanne anbraten.",
      "Kabeljau in Stücken die letzten 8 Minuten im Varoma mitdämpfen bis er gar ist.",
      "Alles mit dem Reis vermengen.",
    ],
    tasteTags:["wenig_fisch_ok","reis","gemuese_viel"],
  },
  {
    id:"blumenkohl-kichererbsen-curry",
    name:"Blumenkohl-Kichererbsen-Curry",
    type:"mittag",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Blumenkohl",grams:150,unit:"g"},
      {item:"Kichererbsen gekocht",grams:120,unit:"g"},
      {item:"Tomaten",grams:80,unit:"g"},
      {item:"Zwiebel",grams:30,unit:"g"},
      {item:"Kurkuma",grams:2,unit:"g"},
      {item:"Ingwer",grams:5,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Zwiebel und Ingwer fein hacken, mit Olivenöl 3 Min/120°C/Stufe 1 anschwitzen.",
      "Blumenkohlröschen, Kichererbsen, Tomaten und Kurkuma zugeben.",
      "15 Min/100°C/Stufe 1 (Linkslauf) köcheln bis Blumenkohl weich ist.",
      "Mit Salz abschmecken, optional mit Naturreis servieren.",
    ],
    tasteTags:["kichererbsen","vegetarisch","gemuese_viel"],
  },
  {
    id:"rosenkohl-haehnchen-pfanne",
    name:"Rosenkohl-Hähnchen-Pfanne mit Kartoffeln",
    type:"mittag",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Hähnchenbrust",grams:150,unit:"g"},
      {item:"Rosenkohl",grams:120,unit:"g"},
      {item:"Kartoffel gekocht",grams:150,unit:"g"},
      {item:"Olivenöl",grams:10,unit:"g"},
      {item:"Thymian",grams:1,unit:"g"},
    ],
    tm7Steps:[
      "Kartoffeln im Varoma 20 Min/Varoma/Stufe 1 dämpfen (Mixtopf 500g Wasser).",
      "Rosenkohl halbieren, die letzten 10 Minuten dazugeben.",
      "Hähnchen parallel in Olivenöl mit Thymian in der Pfanne anbraten.",
      "Alles zusammen anrichten.",
    ],
    seasonalSwap:{von:"Rosenkohl",alternativen:{sommer:"Zucchini",herbst:"Rosenkohl",winter:"Rosenkohl",fruehling:"Brokkoli"}},
    tasteTags:["haehnchen","gemuese_viel"],
  },
  {
    id:"zucchini-haehnchen-auflauf",
    name:"Zucchini-Hähnchen-Auflauf-Basis (TM-Sauce)",
    type:"mittag",
    season:["sommer"],
    portionsBase:1,
    ingredients:[
      {item:"Hähnchenbrust",grams:150,unit:"g"},
      {item:"Zucchini",grams:150,unit:"g"},
      {item:"Tomaten",grams:80,unit:"g"},
      {item:"Feta",grams:30,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Hähnchen würfeln, in Olivenöl 3 Min/120°C/Stufe 1 anbraten.",
      "Tomaten zugeben, 5 Min/100°C/Stufe 1 zu einer Sauce einkochen.",
      "Zucchinischeiben und Sauce in eine Auflaufform schichten, Feta drüber, im Ofen 20 Min/200°C fertig garen (TM7 übernimmt die Sauce, der Ofen das Gratinieren).",
    ],
    tasteTags:["haehnchen","gemuese_viel"],
  },
  // ── SNACKS ──────────────────────────────────────────────────────
  {
    id:"snack-hummus-gemuese",
    name:"Hummus mit Gemüsesticks (TM-Hummus)",
    type:"snack",
    season:["ganzjahr"],
    portionsBase:1,
    ingredients:[
      {item:"Kichererbsen gekocht",grams:100,unit:"g"},
      {item:"Olivenöl",grams:10,unit:"g"},
      {item:"Knoblauch",grams:3,unit:"g"},
      {item:"Karotte",grams:50,unit:"g"},
      {item:"Paprika rot",grams:50,unit:"g"},
    ],
    tm7Steps:[
      "Kichererbsen, Olivenöl, Knoblauch und etwas Salz in den Mixtopf geben.",
      "30 Sek/Stufe 8 zu Hummus pürieren, bei Bedarf etwas Wasser zugeben.",
      "Mit Gemüsesticks (Karotte, Paprika) servieren.",
    ],
    tasteTags:["kichererbsen","vegetarisch","schnell"],
  },
  {
    id:"snack-quark-beeren",
    name:"Quark mit Beeren und Walnüssen",
    type:"snack",
    season:["sommer","fruehling"],
    portionsBase:1,
    ingredients:[
      {item:"Magerquark",grams:150,unit:"g"},
      {item:"Beeren gemischt",grams:80,unit:"g"},
      {item:"Walnüsse",grams:15,unit:"g"},
    ],
    tm7Steps:[
      "Keine TM-Zubereitung nötig – einfach zusammenmischen.",
      "Optional: Beeren kurz im Mixtopf 3 Sek/Stufe 4 anpürieren für eine Sauce.",
    ],
    seasonalSwap:{von:"Beeren gemischt",alternativen:{sommer:"Beeren gemischt",herbst:"Apfel",winter:"Apfel",fruehling:"Beeren gemischt"}},
    tasteTags:["quark","schnell","vegetarisch"],
  },
  {
    id:"snack-edamame",
    name:"Edamame mit Meersalz",
    type:"snack",
    season:["ganzjahr"],
    portionsBase:1,
    ingredients:[
      {item:"Edamame",grams:150,unit:"g"},
    ],
    tm7Steps:[
      "Edamame im Varoma 8 Min/Varoma/Stufe 1 dämpfen (Mixtopf 400g Wasser).",
      "Mit etwas Meersalz bestreuen.",
    ],
    tasteTags:["vegetarisch","schnell","proteinreich"],
  },
  {
    id:"snack-skyr-apfel",
    name:"Skyr mit Apfel und Zimt",
    type:"snack",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Skyr",grams:150,unit:"g"},
      {item:"Apfel",grams:100,unit:"g"},
    ],
    tm7Steps:[
      "Apfel würfeln, mit Skyr mischen.",
      "Optional eine Prise Zimt darüber.",
    ],
    tasteTags:["quark","schnell","vegetarisch"],
  },
  {
    id:"snack-essiggurken-huettenkaese",
    name:"Hüttenkäse mit Essiggurken und Paprika",
    type:"snack",
    season:["ganzjahr"],
    portionsBase:1,
    ingredients:[
      {item:"Hüttenkäse",grams:150,unit:"g"},
      {item:"Essiggurken",grams:40,unit:"g"},
      {item:"Paprika rot",grams:40,unit:"g"},
    ],
    tm7Steps:[
      "Keine TM-Zubereitung nötig – Essiggurken und Paprika klein schneiden, mit Hüttenkäse mischen.",
    ],
    tasteTags:["huettenkaese","schnell","vegetarisch"],
  },
  {
    id:"snack-sauerkraut-feta",
    name:"Sauerkraut-Feta-Salat",
    type:"snack",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Sauerkraut",grams:100,unit:"g"},
      {item:"Feta",grams:40,unit:"g"},
      {item:"Olivenöl",grams:5,unit:"g"},
    ],
    tm7Steps:[
      "Keine TM-Zubereitung nötig – Sauerkraut mit Feta und etwas Olivenöl mischen.",
    ],
    tasteTags:["fermentiert","schnell","vegetarisch"],
  },
  {
    id:"snack-kimchi-reis",
    name:"Kimchi-Reis-Snack",
    type:"snack",
    season:["ganzjahr"],
    portionsBase:1,
    ingredients:[
      {item:"Kimchi",grams:80,unit:"g"},
      {item:"Naturreis",grams:50,unit:"g (roh)"},
    ],
    tm7Steps:[
      "Reis im Varoma 20 Min/Varoma/Stufe 1 dämpfen (Mixtopf 300g Wasser).",
      "Mit Kimchi servieren.",
    ],
    tasteTags:["fermentiert","schnell"],
  },
  // ── WEITERE MITTAGSREZEPTE ──────────────────────────────────────
  {
    id:"dinkel-gemuese-pfanne",
    name:"Dinkel-Gemüse-Pfanne mit Feta",
    type:"mittag",
    season:["sommer","fruehling"],
    portionsBase:1,
    ingredients:[
      {item:"Dinkel Vollkornmehl",grams:60,unit:"g (als Dinkelreis, roh)"},
      {item:"Zucchini",grams:80,unit:"g"},
      {item:"Tomaten",grams:80,unit:"g"},
      {item:"Paprika rot",grams:50,unit:"g"},
      {item:"Feta",grams:40,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Dinkel im Varoma mit 250g Wasser im Mixtopf 25 Min/Varoma/Stufe 1 dämpfen.",
      "Gemüse würfeln, mit Olivenöl 4 Min/120°C/Stufe 1 (Linkslauf) anbraten.",
      "Dinkel und Gemüse vermengen, Feta darüber bröckeln.",
    ],
    seasonalSwap:{von:"Zucchini",alternativen:{sommer:"Zucchini",herbst:"Aubergine",winter:"Sellerie",fruehling:"Zucchini"}},
    tasteTags:["dinkel","vegetarisch","gemuese_viel"],
  },
  {
    id:"thunfisch-kartoffel-salat",
    name:"Thunfisch-Kartoffel-Salat",
    type:"mittag",
    season:["sommer"],
    portionsBase:1,
    ingredients:[
      {item:"Thunfisch Dose",grams:120,unit:"g (Abtropfgewicht)"},
      {item:"Kartoffel gekocht",grams:200,unit:"g"},
      {item:"Tomaten",grams:60,unit:"g"},
      {item:"Essiggurken",grams:30,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Kartoffeln im Varoma 20 Min/Varoma/Stufe 1 dämpfen (Mixtopf 500g Wasser), danach würfeln.",
      "Tomaten und Essiggurken klein schneiden.",
      "Alles mit Thunfisch und Olivenöl vermengen, salzen, pfeffern.",
    ],
    tasteTags:["wenig_fisch_ok","kartoffeln","schnell"],
  },
  {
    id:"kichererbsen-spinat-eintopf",
    name:"Kichererbsen-Spinat-Eintopf",
    type:"mittag",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Kichererbsen gekocht",grams:150,unit:"g"},
      {item:"Spinat",grams:100,unit:"g"},
      {item:"Tomaten",grams:80,unit:"g"},
      {item:"Zwiebel",grams:30,unit:"g"},
      {item:"Knoblauch",grams:5,unit:"g"},
      {item:"Kurkuma",grams:2,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Zwiebel und Knoblauch fein hacken, mit Olivenöl 3 Min/120°C/Stufe 1 anschwitzen.",
      "Kichererbsen, Tomaten und Kurkuma zugeben, 15 Min/100°C/Stufe 1 (Linkslauf) köcheln.",
      "Spinat die letzten 3 Minuten dazugeben, zusammenfallen lassen.",
    ],
    tasteTags:["kichererbsen","vegetarisch","gemuese_viel","ballaststoffreich"],
  },
  {
    id:"haehnchen-kartoffel-curry",
    name:"Hähnchen-Kartoffel-Curry",
    type:"mittag",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Hähnchenbrust",grams:150,unit:"g"},
      {item:"Kartoffel gekocht",grams:150,unit:"g"},
      {item:"Karotte",grams:60,unit:"g"},
      {item:"Zwiebel",grams:30,unit:"g"},
      {item:"Kurkuma",grams:2,unit:"g"},
      {item:"Ingwer",grams:5,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Hähnchen würfeln, mit Öl 3 Min/120°C/Stufe 1 anbraten.",
      "Zwiebel, Ingwer, Kurkuma zugeben, kurz mitschwitzen.",
      "Kartoffeln und Karotten würfeln, dazugeben, mit etwas Wasser 15 Min/100°C/Stufe 1 (Linkslauf) köcheln.",
    ],
    seasonalSwap:{von:"Karotte",alternativen:{sommer:"Zucchini",herbst:"Kürbis",winter:"Pastinake",fruehling:"Karotte"}},
    tasteTags:["haehnchen","gemuese_viel"],
  },
  {
    id:"pute-paprika-quinoa",
    name:"Puten-Paprika-Quinoa-Pfanne",
    type:"mittag",
    season:["sommer","fruehling"],
    portionsBase:1,
    ingredients:[
      {item:"Putenbrust",grams:150,unit:"g"},
      {item:"Quinoa gekocht",grams:150,unit:"g (oder 50g roh)"},
      {item:"Paprika rot",grams:60,unit:"g"},
      {item:"Paprika gelb",grams:60,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Quinoa im Varoma mit 300g Wasser im Mixtopf 15 Min/Varoma/Stufe 1 dämpfen.",
      "Pute und Paprika würfeln, mit Öl in der Pfanne 6-8 Min anbraten.",
      "Mit Quinoa vermengen, salzen, pfeffern.",
    ],
    tasteTags:["pute","quinoa","gemuese_viel"],
  },
  {
    id:"weisse-bohnen-spinat-suppe",
    name:"Weiße-Bohnen-Spinat-Suppe",
    type:"mittag",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Weiße Bohnen",grams:150,unit:"g"},
      {item:"Spinat",grams:80,unit:"g"},
      {item:"Karotte",grams:50,unit:"g"},
      {item:"Zwiebel",grams:30,unit:"g"},
      {item:"Gemüsebrühe",grams:300,unit:"ml"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Zwiebel und Karotte grob schneiden, 5 Sek/Stufe 5 zerkleinern.",
      "Mit Öl 3 Min/120°C/Stufe 1 anschwitzen.",
      "Bohnen und Brühe zugeben, 15 Min/100°C/Stufe 1 köcheln.",
      "Spinat die letzten 3 Minuten dazugeben.",
    ],
    tasteTags:["weisse_bohnen","vegetarisch","ballaststoffreich"],
  },
  {
    id:"blumenkohl-haehnchen-curry",
    name:"Blumenkohl-Hähnchen-Curry",
    type:"mittag",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Hähnchenbrust",grams:150,unit:"g"},
      {item:"Blumenkohl",grams:150,unit:"g"},
      {item:"Tomaten",grams:60,unit:"g"},
      {item:"Zwiebel",grams:30,unit:"g"},
      {item:"Kurkuma",grams:2,unit:"g"},
      {item:"Olivenöl",grams:8,unit:"g"},
    ],
    tm7Steps:[
      "Hähnchen würfeln, mit Öl 3 Min/120°C/Stufe 1 anbraten.",
      "Zwiebel, Kurkuma, Tomaten zugeben.",
      "Blumenkohlröschen dazu, 15 Min/100°C/Stufe 1 (Linkslauf) köcheln bis weich.",
    ],
    tasteTags:["haehnchen","gemuese_viel"],
  },
  // ── WEITERE SNACKS ──────────────────────────────────────────────
  {
    id:"snack-oliven-feta",
    name:"Oliven-Feta-Teller",
    type:"snack",
    season:["ganzjahr"],
    portionsBase:1,
    ingredients:[
      {item:"Oliven schwarz",grams:50,unit:"g"},
      {item:"Feta",grams:50,unit:"g"},
      {item:"Tomaten",grams:60,unit:"g"},
    ],
    tm7Steps:[
      "Keine TM-Zubereitung nötig – einfach anrichten.",
    ],
    tasteTags:["fermentiert","schnell","vegetarisch"],
  },
  {
    id:"snack-apfel-mandeln",
    name:"Apfel mit Mandeln",
    type:"snack",
    season:["herbst","winter"],
    portionsBase:1,
    ingredients:[
      {item:"Apfel",grams:150,unit:"g"},
      {item:"Mandeln",grams:20,unit:"g"},
    ],
    tm7Steps:[
      "Keine TM-Zubereitung nötig.",
    ],
    tasteTags:["schnell","vegetarisch"],
  },
];
